export const CREATECHAT_CHAT_REQUEST = "GETORCREATECHAT_CHAT_REQUEST";
export const CREATECHAT_CHAT_SUCCESS = "GETORCREATECHAT_CHAT_SUCCESS";
export const CREATECHAT_CHAT_FAIL = "GETORCREATECHAT_CHAT_FAIL";

export const CREATEGROUP_CHAT_REQUEST = "CREATEGROUP_CHAT_REQUEST";
export const CREATEGROUP_CHAT_SUCCESS = "CREATEGROUP_CHAT_SUCCESS";
export const CREATEGROUP_CHAT_FAIL = "CREATEGROUP_CHAT_FAIL";

// get chat
export const GETALL_CHAT_REQUEST = "GETALL_CHAT_REQUEST";
export const GETALL_CHAT_SUCCESS = "GETALL_CHAT_SUCCESS";
export const GETALL_CHAT_FAIL = "GETALL_CHAT_FAIL";



export const REMOVEGROUP_CHAT_REQUEST = "REMOVEGROUP_CHAT_REQUEST";
export const REMOVEGROUP_CHAT_SUCCESS = "REMOVEGROUP_CHAT_SUCCESS";
export const REMOVEGROUP_CHAT_FAIL = "REMOVEGROUP_CHAT_FAIL";
export const REMOVEGROUP_CHAT_RESET = "REMOVEGROUP_CHAT_RESET";

export const ADDTOGROUP_CHAT_REQUEST = "ADDTOGROUP_CHAT_REQUEST";
export const ADDTOGROUP_CHAT_SUCCESS = "ADDTOGROUP_CHAT_SUCCESS";
export const ADDTOGROUP_CHAT_FAIL = "ADDTOGROUP_CHAT_FAIL";
export const ADDTOGROUP_CHAT_RESET = "ADDTOGROUP_CHAT_RESET";

export const RENAMEGROUP_CHAT_REQUEST = "RENAMEGROUP_CHAT_REQUEST";
export const RENAMEGROUP_CHAT_SUCCESS = "RENAMEGROUP_CHAT_SUCCESS";
export const RENAMEGROUP_CHAT_FAIL = "RENAMEGROUP_CHAT_FAIL";
export const RENAMEGROUP_CHAT_RESET = "RENAMEGROUP_CHAT_RESET";

// clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS"