export const GETALL_MESSAGE_REQUEST = "GETALL_MESSAGE_REQUEST";
export const GETALL_MESSAGE_SUCCESS = "GETALL_MESSAGE_SUCCESS";
export const GETALL_MESSAGE_FAIL = "GETALL_MESSAGE_FAIL";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";


//clear errors
export const CLEAR_ERRORS = "CLEAR_ERRORS"