// Register user

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"


// LOGIN 
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";



// LOAD USER
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";


// LOGOUT USER
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

// clear errors

export const CLEAR_ERRORS = "CLEAR_ERRORS"