// Register user

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"


// LOGIN 
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";


// clear errors

export const CLEAR_ERRORS = "CLEAR_ERRORS"